package dev.simplified.client.subnet.pool;

import dev.simplified.client.ratelimit.RateLimitConfig;
import dev.simplified.client.request.Contract;
import dev.simplified.client.route.Route;

/**
 * Minimal {@link Contract} used by subnet-package tests. The route points at a
 * disconnected localhost port; no actual HTTP traffic is generated by these
 * tests, only the rotation-layer logic is exercised.
 */
@Route(value = "127.0.0.1:0", rateLimit = @RateLimitConfig(unlimited = true))
interface TestContract extends Contract {
}
