package dev.simplified.client.response;

import dev.simplified.client.request.Request;
import dev.simplified.collection.Concurrent;
import dev.simplified.collection.ConcurrentList;
import dev.simplified.collection.ConcurrentMap;
import dev.simplified.collection.tuple.pair.Pair;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import org.jetbrains.annotations.NotNull;

import java.util.Collection;
import java.util.Map;

/**
 * Top-level interface representing a fully-resolved HTTP response, providing typed access
 * to the deserialized body, status code, headers, network details, and originating request.
 * <p>
 * Implementations carry the complete response lifecycle: the {@link Request} that initiated
 * the call, the {@link HttpStatus} returned by the server, the response headers (with
 * internal instrumentation headers stripped), and a {@link NetworkDetails} snapshot
 * capturing timing and TLS metadata. Convenience methods such as
 * {@link #getCloudflareCacheStatus()} and {@link #isError()} provide quick access to
 * commonly needed response characteristics.
 * <p>
 * A default implementation is provided by the inner class {@link Impl}.
 *
 * @param <T> the deserialized type of the response body
 * @see Request
 * @see HttpStatus
 * @see NetworkDetails
 */
public interface Response<T> {

    /**
     * Retrieves the Cloudflare CDN cache status from the {@code CF-Cache-Status} response
     * header.
     * <p>
     * Looks up the {@link CloudflareCacheStatus#HEADER_KEY} in the response headers and
     * resolves its value to a {@link CloudflareCacheStatus} constant. If the header is
     * missing or contains an unrecognized value, {@link CloudflareCacheStatus#UNKNOWN}
     * is returned.
     *
     * @return the {@link CloudflareCacheStatus} indicating the caching disposition of this response
     */
    default @NotNull CloudflareCacheStatus getCloudflareCacheStatus() {
        return this.getHeaders()
            .getOptional(CloudflareCacheStatus.HEADER_KEY)
            .flatMap(ConcurrentList::findFirst)
            .map(CloudflareCacheStatus::of)
            .orElse(CloudflareCacheStatus.UNKNOWN);
    }

    /** The deserialized body of the HTTP response, decoded into the parameterized type {@code T}. */
    @NotNull T getBody();

    /** The network-level timing and TLS metadata captured during the request/response cycle. */
    @NotNull NetworkDetails getDetails();

    /**
     * The response headers as an unmodifiable concurrent map, excluding internal
     * instrumentation headers (those prefixed with {@code X-Internal-}).
     */
    @NotNull ConcurrentMap<String, ConcurrentList<String>> getHeaders();

    /** The originating {@link Request} that produced this response. */
    @NotNull Request getRequest();

    /** The {@link HttpStatus} of the response, indicating the numeric code and its classification. */
    @NotNull HttpStatus getStatus();

    /**
     * Determines whether this response represents an error condition.
     * <p>
     * Delegates to {@link HttpState#isError()} on the state associated with this
     * response's {@link HttpStatus}.
     *
     * @return {@code true} if the response status belongs to an error state;
     *         {@code false} otherwise
     */
    default boolean isError() {
        return this.getStatus().getState().isError();
    }

    /**
     * Converts a standard {@link Map} of header names to value collections into an
     * unmodifiable {@link ConcurrentMap}, filtering out empty entries and internal
     * instrumentation headers.
     * <p>
     * Internal headers (identified by {@link NetworkDetails#isInternalHeader(String)})
     * are excluded because they carry interceptor-injected timing data that is not part
     * of the actual HTTP response.
     *
     * @param headers the raw response headers map to convert
     * @return an unmodifiable {@link ConcurrentMap} of header names to unmodifiable
     *         {@link ConcurrentList} value lists, with internal headers removed
     */
    static @NotNull ConcurrentMap<String, ConcurrentList<String>> getHeaders(@NotNull Map<String, Collection<String>> headers) {
        return headers.entrySet()
            .stream()
            .filter(entry -> !entry.getValue().isEmpty())
            .filter(entry -> !NetworkDetails.isInternalHeader(entry.getKey()))
            .map(entry -> Pair.of(
                entry.getKey(),
                (ConcurrentList<String>) Concurrent.newUnmodifiableList(entry.getValue())
            ))
            .collect(Concurrent.toUnmodifiableMap());
    }

    /**
     * Default immutable implementation of {@link Response}, storing all response
     * components as final fields initialized via constructor injection.
     * <p>
     * All accessors are generated by Lombok's {@link Getter} annotation.
     *
     * @param <T> the deserialized type of the response body
     */
    @Getter
    @RequiredArgsConstructor
    class Impl<T> implements Response<T> {

        /** The deserialized response body. */
        private final @NotNull T body;

        /** The network timing and TLS metadata for this response. */
        private final @NotNull NetworkDetails details;

        /** The HTTP status code and classification for this response. */
        private final @NotNull HttpStatus status;

        /** The originating request that produced this response. */
        private final @NotNull Request request;

        /** The response headers, with internal instrumentation headers excluded. */
        private final @NotNull ConcurrentMap<String, ConcurrentList<String>> headers;

    }

}
